---
parser: '@babel/eslint-parser'
parserOptions:
  ecmaVersion: 6
  sourceType: 'module'
  requireConfigFile: false
  ecmaFeatures:
    jsx: true
  babelOptions:
    presets:
      - '@babel/preset-react'
env:
  browser: true
  es6: true
  node: true
  jest: true
globals:
  expect: true
  __DEV__: true
plugins:
  - import
  - jsx-a11y
  - prettier
extends:
  - plugin:prettier/recommended
  - prettier
rules:
  react/state-in-constructor: off
  react/destructuring-assignment: off
  import/no-cycle: off
  react/forbid-prop-types: off
  react/jsx-filename-extension: off
overrides:
  - files: ['*.test.js', '*.test.jsx']
    rules:
      react/jsx-props-no-spreading: off
  - files: ['**/*.stories.*']
    rules:
      import/no-anonymous-default-export": off
      react/jsx-props-no-spreading: off
